// Generated by CoffeeScript 1.3.1
var Action;

Action = (function() {

  Action.name = 'Action';

  function Action() {}

  Action.frameCount;

  Action.selfHitboxes;

  Action.attackHitboxes;

  Action.textures;

  Action.triggerConditions;

  Action.interruptConditions;

  Action.isHostile;

  return Action;

})();
