// Generated by CoffeeScript 1.3.1
var Action;

Action = (function() {

  Action.name = 'Action';

  function Action() {}

  Action.frameCounts;

  Action.selfHitboxes;

  Action.attackHitboxes;

  Action.textures;

  Action.triggerConditions;

  Action.interruptConditions;

  Action.interruptActions;

  Action.endActions;

  Action.isHostile;

  return Action;

})();
