// Generated by CoffeeScript 1.3.1
var Animation;

Animation = (function() {

  Animation.name = 'Animation';

  function Animation(frameCount, resources) {
    this.currentFrame = 0;
    this.frameCount = frameCount;
    this.frameRemainder = 0;
    this.resources = resources;
    this.textures = [];
    this.loaded = false;
  }

  Animation.prototype.consumeTime = function(elapsed) {
    var frames;
    frames = (elapsed + this.frameRemainder) % (1000 / e.fps);
    this.frameRemainder = (elapsed + this.frameRemainder) - (frames * (1000 / e.fps));
    return this.currentFrame = (this.currentFrame + frames) % this.frameCount;
  };

  Animation.prototype.reset = function() {
    return this.currentFrame = 0;
  };

  Animation.prototype.texture = function() {
    return this.textures[this.currentFrame];
  };

  Animation.prototype.load = function() {
    var file, _i, _len, _ref;
    _ref = this.resources;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      this.textures.push(new GLTexture('resources/' + file));
    }
    return null;
  };

  Animation.prototype.unload = function() {
    var texture, _i, _len, _ref;
    _ref = this.textures;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      texture = _ref[_i];
      texture["delete"]();
    }
    this.textures = [];
    return null;
  };

  return Animation;

})();
