// Generated by CoffeeScript 1.3.1
var Application;

Application = (function() {

  Application.name = 'Application';

  Application.game;

  Application.running;

  Application.lastUpdate;

  function Application() {
    this.game = new Game();
    this.running = false;
    document.onkeydown = this.game.keyDown(event);
  }

  Application.prototype.runGame = function() {
    this.running = true;
    while (this.running) {
      setInterval(tick, 1000 / 60);
    }
    return null;
  };

  Application.prototype.tick = function() {
    var thisUpdate, timeDiff;
    thisUpdate = Date().Now;
    timeDiff = thisUpdate - this.lastUpdate;
    theGame.draw();
    theGame.update(timeDiff);
    return getElementById('game_canvas').text = timeDiff;
  };

  return Application;

})();
