// Generated by CoffeeScript 1.3.1
var Application, application;

Application = (function() {

  Application.name = 'Application';

  function Application() {}

  Application.game;

  Application.running;

  Application.lastUpdate;

  Application.updateCallback;

  Application.prototype.init = function() {
    webGLStart();
    this.game = new Game();
    this.running = false;
    this.lastUpdate = new Date().getTime();
    return document.onkeydown = this.game.keyDown(event);
  };

  Application.prototype.tick = function() {
    var thisUpdate, timeDiff;
    if (!application.running) {
      clearInterval(application.updateCallback);
    }
    thisUpdate = new Date().getTime();
    timeDiff = thisUpdate - application.lastUpdate;
    application.lastUpdate = thisUpdate;
    application.game.draw();
    application.game.update(timeDiff);
    return document.getElementById('text').textContent = timeDiff;
  };

  Application.prototype.runGame = function() {
    this.init();
    this.running = true;
    this.updateCallback = setInterval(this.tick, 1000 / 60);
    return null;
  };

  return Application;

})();

application = new Application();
