// Generated by CoffeeScript 1.3.1
var Application, a;

Application = (function() {

  Application.name = 'Application';

  function Application() {
    this.lastUpdate = 0;
    this.request = undefined;
    var that = this;
    this.gameLoop = function() {
      var timeDiff;
      if (!e.running) {
        cancelAnimFrame(a.request);
      }
      timeDiff = new Date().getTime() - that.lastUpdate;
      that.lastUpdate = that.lastUpdate + timeDiff;
      e.update(timeDiff);
      e.draw();
      that.request = requestAnimFrame(that.gameLoop /*, should also pass canvas here */);
    };

  }

  Application.prototype.run = function() {
    e.running = true;
    e.initialize();
    this.gameLoop();
  };

  return Application;

})();

a = new Application();
