// Generated by CoffeeScript 1.3.1
var Background;

Background = (function() {

  Background.name = 'Background';

  function Background(file) {
    var that;
    this.loaded = false;
    this.sprite = null;
    this.xmlHttp = new XMLHttpRequest();
    that = this;
    this.xmlHttp.onreadystatechanged = function() {
      var dom;
      dom = that.xmlHttp.requestXml;
      that.sprite = new Sprite(dom.getElementsByTagName('Sprite')[0]);
      that.loaded = true;
      return alert('lol');
    };
    this.xmlHttp.open('GET', file, false);
    this.xmlHttp.send();
    this.model = mat4.create();
    mat4.identity(this.model);
  }

  Background.prototype.draw = function(camera) {
    if ((this.sprite != null) && this.sprite.loaded) {
      return this.sprite.draw(camera, this.model);
    }
  };

  Background.prototype.load = function() {
    return null;
  };

  Background.prototype.unload = function() {
    this.sprite.unload();
    return null;
  };

  return Background;

})();
