// Generated by CoffeeScript 1.3.1
var Camera2D;

Camera2D = (function() {

  Camera2D.name = 'Camera2D';

  function Camera2D() {
    this.mvp = mat4.create();
    this.pMatrix = mat4.create();
    this.vMatrix = mat4.create();
    this.tX = 0;
    this.tY = 0;
    this.rA = 0;
  }

  Camera2D.prototype.computeMVP = function(model) {
    model.translate(this.tX, this.tY, 0);
    model.rotate(this.rA, 0, 0, 1);
    Matrix.multiplyMM(this.mvp, 0, this.vMatrix, 0, model, 0);
    Matrix.multiplyMM(this.mvp, 0, this.pMatrix, 0, this.mvp, 0);
    return this.mvp;
  };

  Camera2D.prototype.lookAt = function(x, y) {
    return Matrix.setLookAtM(this.vMatrix, 0, x, y, 3, x, y, 0, 0, 1, 0);
  };

  Camera2D.prototype.setBounds = function(left, right, bottom, top, near, far) {
    return Matrix.orthoM(this.pMatrix, 0, left, right, bottom, top, near, far);
  };

  Camera2D.prototype.setRotate = function(angle) {
    return this.rA = angle;
  };

  Camera2D.prototype.setTranslate = function(x, y) {
    this.tX = x;
    return this.tY = y;
  };

  return Camera2D;

})();
