// Generated by CoffeeScript 1.3.1
var Engine, e;

Engine = (function() {

  Engine.name = 'Engine';

  function Engine() {
    this.fps = 30;
    this.initialized = false;
    this.running = false;
    this.worldCam = null;
    this.basicProgram = 'basic';
  }

  Engine.prototype.draw = function() {
    return gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
  };

  Engine.prototype.initialize = function() {
    var canvas;
    canvas = document.getElementById('game_canvas');
    glUtils.initWebGL(canvas);
    if ((typeof gl !== "undefined" && gl !== null)) {
      gl.viewport(0, 0, canvas.width, canvas.height);
      gl.clearColor(0.0, 0.0, 0.0, 1.0);
      gl.enable(gl.DEPTH_TEST);
      gl.depthFunc(gl.LEQUAL);
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    } else {
      this.running = false;
    }
    this.worldCam = new Camera2D();
    this.worldCam.lookAt(0, 0);
    this.worldCam.setBounds(-1, 1, -1, 1, 4, 0);
    this.worldCam.setRotate(0);
    this.worldCam.setTranslate(0, 0);
    return this.initialized = true;
  };

  Engine.prototype.update = function(elapsed) {
    return document.getElementById('text').textContent = elapsed;
  };

  return Engine;

})();

e = new Engine();
