// Generated by CoffeeScript 1.3.1
var Game;

Game = (function() {

  Game.name = 'Game';

  function Game() {}

  Game.currentKey = null;

  Game.prototype.draw = function() {
    return null;
  };

  Game.prototype.keyDown = function(keyEvent) {
    return true;
  };

  Game.prototype.update = function(time) {
    return null;
  };

  return Game;

})();
