// Generated by CoffeeScript 1.3.1
var GLProgram;

GLProgram = (function() {

  GLProgram.name = 'GLProgram';

  function GLProgram(vScript, fScript) {
    this.vScript = vScript;
    this.fScript = fScript;
    this.program = glUtils.createProgram(vScript, fScript);
    this.matrixHandle = glUtils.getUniform(program, "uMVPMatrix");
    this.samplerHandle = glUtils.getUniform(program, "uSampler2D");
    this.textureHandle = glUtils.getAttrib(program, "aTexCoord");
    this.vertexHandle = glUtils.getAttrib(program, "aVertCoord");
  }

  GLProgram.prototype["delete"] = function() {
    return glUtils.deleteProgram(this.program);
  };

  return GLProgram;

})();
