// Generated by CoffeeScript 1.3.1
var GLTexture;

GLTexture = (function() {

  GLTexture.name = 'GLTexture';

  function GLTexture(imageFile) {
    var image, loaded, texture;
    loaded = false;
    this.texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, this.texture);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array([255,0,255,255]));
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    image = new Image();
    var that = this;
    image.onload = function() {
      loaded = true;
      gl.bindTexture(gl.TEXTURE_2D, that.texture);
      return gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image);
    };
    image.src = imageFile;
    function secretTexture() { return texture; };

    function secretLoaded() { return loaded; };

    this.isLoaded = function() {
      return secretLoaded();
    };
    this.getTexture = function() {
      return secretTexture();
    };
  }

  GLTexture.prototype["delete"] = function() {
    return glUtils.deleteTexture(this.getTexture());
  };

  return GLTexture;

})();
