// Generated by CoffeeScript 1.3.1
var GlTexture;

GlTexture = (function() {

  GlTexture.name = 'GlTexture';

  function GlTexture(imageFile) {
    var image, isLoaded, texture;
    isLoaded = false;
    texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, this.texture);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    image = new Image();
    image.onload = function() {
      this.isLoaded = true;
      gl.bindTexture(gl.TEXTURE_2D, this.texture);
      return gl.texImage2D(gl.TEXTURE_2D, 0, image, true);
    };
    image.src = imageFile;
    function secretTexture() { return texture; };

    function secretLoaded() { return isLoaded; };

    this.isLoaded = function() {
      return secretLoaded();
    };
    this.getTexture = function() {
      return secretTexture();
    };
  }

  GlTexture.prototype["delete"] = function() {
    return glUtils.deleteTexture(this.getTexture());
  };

  return GlTexture;

})();
