// Generated by CoffeeScript 1.3.1
var Mesh;

Mesh = (function() {

  Mesh.name = 'Mesh';

  function Mesh(vert, tex) {
    this.size = vert.length;
    this.vertexCoords = vert;
    this.texCoords = tex;
    this.vertBuffer = null;
    this.texBuffer = null;
    this.loaded = false;
  }

  Mesh.prototype.load = function() {
    this.texBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, this.texBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.texCoords, gl.STATIC_DRAW);
    this.vertBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, this.vertBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.vertCoords, gl.STATIC_DRAW);
    return this.loaded = true;
  };

  Mesh.prototype.unload = function() {
    gl.deleteBuffer(this.texBuffer);
    gl.deleteBuffer(this.vertBuffer);
    return this.loaded = false;
  };

  return Mesh;

})();
