// Generated by CoffeeScript 1.3.1
var ResourceDepot, resourceDepot;

ResourceDepot = (function() {
  var getJSON, init;

  ResourceDepot.name = 'ResourceDepot';

  function ResourceDepot() {}

  ResourceDepot.path;

  init = function() {
    return this.path = "resources/";
  };

  getJSON = function(file, callback) {
    var request;
    request = new XMLHttpRequest();
    request.open("GET", file, true);
    if (request.overrideMimeType) {
      request.overrideMimeType('application/json');
    }
    request.onreadystatechange = function() {
      if (request.readyState === 4) {
        if (request.status === 404) {
          return console.log("ERROR: file '{# file}' does not exist!");
        } else {
          return callback(request.responseText);
        }
      }
    };
    return request.send();
  };

  return ResourceDepot;

})();

resourceDepot = new ResourceDepot();

resourceDepot.init();
