// Generated by CoffeeScript 1.3.1
var StageBackground;

StageBackground = (function() {

  StageBackground.name = 'StageBackground';

  function StageBackground(filename) {
    this.vertCoords = new Float32Array([-1, -1, 0, -1, 1, 0, 1, 1, 0, -1, -1, 0, 1, 1, 0, 1 - 1, 0]);
    this.texCoords = new Float32Array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0]);
    this.texture = new GLTexture(filename);
    this.model = mat4.create();
    mat4.identity(this.model);
    this.texBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, this.texBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.texCoords, gl.STATIC_DRAW);
    this.vertBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, this.vertBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.vertCoords, gl.STATIC_DRAW);
  }

  StageBackground.prototype.draw = function(camera) {
    glUtils.useTexture(this.texture);
    glUtils.useCamera(camera, this.model);
    glUtils.setVertexBuffer(this.vertBuffer, 0, 0);
    glUtils.setTextureBuffer(this.texBuffer, 0, 0);
    return gl.drawArrays(gl.TRIANGLES, 0, 6);
  };

  return StageBackground;

})();
