// Generated by CoffeeScript 1.3.1
var StageBackground;

StageBackground = (function() {

  StageBackground.name = 'StageBackground';

  StageBackground.texture;

  StageBackground.packedBuffer;

  StageBackground.vertBuffer;

  function StageBackground(filename) {
    this.packedBuffer = new Float32Array([-1.0, -1.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, -1.0, -1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, -1.0, 0.0, 1.0, 0.0]);
    this.vertBuffer = new Float32Array([-1.0, -1.0, 0.0, -1.0, 1.0, 0.0, 1.0, 1.0, 0.0, -1.0, -1.0, 0.0, 1.0, 1.0, 0.0, 1.0, -1.0, 0.0]);
    this.texBuffer = new Float32Array([0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]);
    loadTexture(filename, function(tex) {
      return this.texture = tex;
    });
  }

  StageBackground.prototype.draw = function() {
    var vertBuffer;
    vertBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, vertBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.vertBuffer, gl.STATIC_DRAW);
    gl.vertexAttribPointer(shaderProgram.positionLocation, 3, gl.FLOAT, false, 0, 0);
    gl.enableVertexAttribArray(shaderProgram.positionLocation);
    /*
        gl.activeTexture gl.TEXTURE0
        gl.bindTexture gl.TEXTURE_2D, @texture
        gl.uniform1i shaderProgram.samplerLocation, 0
    
        texBuffer = gl.createBuffer()
        gl.bindBuffer gl.ARRAY_BUFFER, texBuffer
        gl.bufferData gl.ARRAY_BUFFER, @texBuffer, gl.STATIC_DRAW
    
        gl.vertexAttribPointer shaderProgram.texCoordLocation, 2, gl.FLOAT, false, 0, 0
        gl.enableVertexAttribArray shaderProgram.texCoordLocation
    */

    return gl.drawArrays(gl.TRIANGLES, 0, 6);
  };

  return StageBackground;

})();
