// Generated by CoffeeScript 1.3.1
var TriangleTest;

TriangleTest = (function() {

  TriangleTest.name = 'TriangleTest';

  function TriangleTest() {
    this.vertCoords = new Float32Array([0, 0, 0, 1, 1, 0, 0, 1, 0]);
    this.texCoords = new Float32Array([0, 0, 1, 1, 0, 1]);
    this.texture = new GLTexture('resources/red.png');
    this.model = mat4.create();
    mat4.identity(this.model);

    this.vertBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, this.vertBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.vertCoords, gl.STATIC_DRAW);

    this.texBuffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, this.texBuffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.texCoords, gl.STATIC_DRAW);
  }

  TriangleTest.prototype.draw = function(camera) {
    glUtils.useTexture(this.texture);
    glUtils.useCamera(camera, this.model);
    glUtils.setVertexBuffer(this.vertBuffer, 0, 0);
    glUtils.setTextureBuffer(this.texBuffer, 0, 0);
    return gl.drawArrays(gl.TRIANGLES, 0, 3);
  };

  return TriangleTest;

})();
